version: '3.0'

services:
  web-server:
    build:
      context: /etc/docker-config
      dockerfile: DockerfilePHP.txt
    container_name: web-server
    depends_on:
    - db-server
    volumes:
    - /home/admin/QDS:/var/www/html/QDS
    ports:
    - 8000:80

  db-server:
    container_name: db-server
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    volumes:
    - /home/admin/QDS:/var/lib/mysql
    ports:
    - 3306:3306


