version: '3.0'

services:
  web-server:
    build:
      context: /etc/docker-config
      dockerfile: DockerfilePHP.txt
    container_name: web-server
    depends_on:
    - db-server
    volumes:
    - /home/admin:/var/www/html
    ports:
    - 8000:80

  db-server:
    container_name: db-server
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: QDS
      MYSQL_ROOT_PASSWORD: qds000L
      MYSQL_USER: adminQDS
      MYSQL_PASSWORD: qds000L
    ports:
    - 6033:3306


